import "./globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/AntdRegistry";
import { Inter } from "next/font/google";
import CustomProvider from "./lib/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FILL",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="root" className={inter.className}>
        <StyledComponentsRegistry>
          <CustomProvider>{children}</CustomProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
